[env:dfrobot_firebeetle2_esp32e]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
monitor_speed = 115200

upload_port = COM5    
monitor_port = COM5

lib_deps = 
    adafruit/Adafruit MCP23017 Arduino Library @ ^2.3.0
    lemmingdev/ESP32-BLE-Gamepad @ 0.5.2
    olikraus/U8g2 @ ^2.34.15
    h2zero/NimBLE-Arduino @ 1.4.1

build_flags = -Wno-write-strings